export const siteNav = [
  { key: 'about', label: 'Über uns', href: 'index.html' },
  { key: 'social', label: 'Soziales', href: 'soziales.html' },
  { key: 'food', label: 'Food', href: 'food.html' },
  { key: 'forum', label: 'Forum', href: 'forum.html' },
]

export const competitionFacts = {
  season: 'Science League 2025/2026',
  brand: 'bre-delicious',
  title: 'FoodConnectMarkt',
  subtitle: 'Ein Markt für frisches Essen, gemeinsames Lernen und echte Nachbarschaft.',
  description:
    'Für die zdi Science League entwickelt das Team bre-delicious einen FoodConnectMarkt, der Vertical Farming, Einkauf, Bildung und soziale Angebote in einem praktischen Konzept verbindet.',
  intro:
    'Die Website soll nicht nur erklären, was die Idee ist, sondern zeigen, wie sie sich im Alltag anfühlt: klar, vertrauenswürdig, nutzbar und offen für verschiedene Zielgruppen.',
  links: {
    competition: 'https://mint-community.de/scienceleague/',
    team: 'https://mint-community.de/science-league-teams/bre-delicious-saison-2025-2026/',
  },
}

export const heroStats = [
  {
    value: '68 %',
    label: 'der Weltbevölkerung werden bis 2050 in Städten leben',
  },
  {
    value: '~20 %',
    label: 'der CO₂-Emissionen aus Lebensmitteln entstehen durch Transport',
  },
  {
    value: '2 Türme',
    label: 'und ein Keller bilden den FoodConnectMarkt',
  },
]

export const trustHighlights = [
  'Lokal anbauen: frische Produkte direkt am Verkaufsort, ohne weite Transportwege',
  'Gemeinschaft stärken: fünf barrierefreie Etagen für Einkauf, Lernen und Begegnung',
  'Selbstversorgung fördern: Workshops zum Anbau auf Balkon und in der Wohnung',
]

export const buildingParts = [
  {
    badge: 'ConnectMarkt',
    sublabel: '5 Etagen · Kreisförmig',
    heading: 'Begegnung & Verkauf',
    text: 'Der soziale Turm. Kinderecke und Lernplätze im Erdgeschoss, barrierefreie Verkaufsfläche mit smarten Einkaufswagen im ersten Stock, Restaurant mit eigenem Gemüse im dritten Stock, Seminarräume und Praxisanbauflächen in den oberen Etagen.',
  },
  {
    badge: 'Gemüseturm',
    sublabel: '10 Etagen · Bohnenform',
    heading: 'Vertical Farming',
    text: 'Der Produktionsturm. Die Bohnenform maximiert die horizontale Fläche und behält die Windresistenz eines ovalen Querschnitts. Alle Etagen sind dem kontrollierten Gemüseanbau gewidmet — mit automatischer Bewässerung und optimiertem Licht.',
  },
  {
    badge: 'Keller',
    sublabel: 'Logistik & Technik',
    heading: 'Das Rückgrat',
    text: 'Warenlager, Heizung, Strom- und Wasserversorgung sowie Kontrolleinheiten liegen im Untergrund — damit oberirdisch jeder Quadratmeter für Grünanlagen und soziale Räume frei bleibt.',
  },
]

export const services = [
  {
    badge: 'Erdgeschoss',
    title: 'Gemeinschaft & offene Räume',
    text: 'Das Erdgeschoss ist offen für alle: eine betreute Kinderecke, ruhige Lernplätze und Informationsstände laden ein, ohne Einkaufsdruck.',
    details: ['betreute Kinderecke', 'ruhige Lerninseln für Schüler*innen', 'Infostände zu allen Angeboten'],
  },
  {
    badge: 'Restaurant · 3. Etage',
    title: 'Restaurant mit eigenem Gemüse',
    text: 'Frisch gekocht aus dem eigenen Anbau. Die Ernte aus dem Gemüseturm landet direkt in der Küche — und als Produkt im Regal, zum Beispiel als Tomatensauce.',
    details: ['Gerichte aus vertikalem Anbau', 'Weiterverarbeitung zu Marktprodukten', 'lokal produziert, kurze Wege'],
  },
  {
    badge: 'Workshops · 4. & 5. Etage',
    title: 'Selbstversorgung lernen',
    text: 'Wir sind realistisch: Unser Markt allein kann keine ganze Stadt versorgen. Deshalb zeigen wir, wie man selbst auf dem Balkon oder in der Wohnung Gemüse anbaut.',
    details: ['Theorie in Seminarräumen (4. Etage)', 'Praxis an echten Anbauanlagen (5. Etage)', 'Ernte wird im Markt verkauft'],
  },
  {
    badge: 'Flexible Nutzung',
    title: 'Seminare, Nachhilfe & Feiern',
    text: 'Kein Raum soll leer stehen. Die Seminarräume sind mehrzweckfähig — für Kurse, Nachhilfe, Geburtstagsfeiern oder Vereinstreffen.',
    details: ['mietbare Seminarräume', 'Nachhilfe und Lernzeit', 'private Veranstaltungen möglich'],
  },
]

export const productCategories = ['Alle', 'Wurzelgemüse', 'Blattgemüse', 'Fruchtgemüse', 'Kräuter & Früchte']

export const products = [
  // ── Ebene 1 & 2: Wurzel- und Knollengemüse (Ebbe-Flut-Tische, Vollspektrum-LEDs) ──
  {
    id: 'karotten',
    name: 'Karotten',
    category: 'Wurzelgemüse',
    price: 2.2,
    unit: 'pro 500 g',
    stockLabel: 'Erntebereit',
    stockLevel: 'fresh',
    image: '/images/products/karotten.jpg',
    description: 'Aus Ebene 1 & 2 unseres Gemüseturms — angebaut auf Ebbe-Flut-Tischen mit tiefen Substratwannen für optimales Wurzelwachstum unter Vollspektrum-LEDs.',
    origin: 'Gemüseturm · Ebene 1 & 2',
    row: 'A2',
    badge: 'Frisch geerntet',
    tags: ['Ebbe-Flut', 'Vollspektrum-LED', 'Wurzelgemüse'],
  },
  {
    id: 'radieschen',
    name: 'Radieschen',
    category: 'Wurzelgemüse',
    price: 2.0,
    unit: 'pro Bund',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/radieschen.png',
    description: 'Knackige Radieschen aus den unteren Anbauetagen — dank Lastenaufzug direkt nebenan täglich frisch im Markt.',
    origin: 'Gemüseturm · Ebene 1 & 2',
    row: 'A5',
    badge: 'Täglich frisch',
    tags: ['Ebbe-Flut', 'knackig', 'regional'],
  },
  {
    id: 'pastinaken',
    name: 'Pastinaken',
    category: 'Wurzelgemüse',
    price: 2.8,
    unit: 'pro 400 g',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/pastinaken.jpg',
    description: 'Süßlich-würzige Pastinaken aus den Ebbe-Flut-Tischen in Etage 1 & 2 — kurzer Weg zum Lastenaufzug garantiert schonenden Transport.',
    origin: 'Gemüseturm · Ebene 1 & 2',
    row: 'B1',
    badge: 'Wochenmarkt-Klassiker',
    tags: ['Substratwanne', 'wurzelfrisch', 'lokal'],
  },
  {
    id: 'lauch',
    name: 'Lauch',
    category: 'Wurzelgemüse',
    price: 1.9,
    unit: 'pro Stange',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/lauch.jpg',
    description: 'Frischer Lauch aus den tiefen Substratwannen in Etage 1 & 2 — ideales Fundament für Suppen, Eintöpfe und herzhafte Pfannengerichte.',
    origin: 'Gemüseturm · Ebene 1 & 2',
    row: 'B4',
    badge: 'Küchenfavorit',
    tags: ['hydroponisch', 'erntefrisch', 'vielseitig'],
  },

  // ── Ebene 3 & 4: Blattgemüse (A-Frames / 10-lagige Regale, blaues LED-Spektrum) ──
  {
    id: 'kopfsalat',
    name: 'Kopfsalat',
    category: 'Blattgemüse',
    price: 2.5,
    unit: 'pro Kopf',
    stockLabel: 'Erntebereit',
    stockLevel: 'fresh',
    image: '/images/products/romana-salat.jpg',
    description: 'Massenerntefähiges Blattgemüse aus den 10-lagigen Regalsystemen in Etage 3 & 4 — schnelles Wachstum durch blau betontes LED-Spektrum.',
    origin: 'Gemüseturm · Ebene 3 & 4',
    row: 'C3',
    badge: 'Heute empfohlen',
    tags: ['A-Frame', 'blaues LED', 'Massenernte'],
  },
  {
    id: 'spinat',
    name: 'Spinat',
    category: 'Blattgemüse',
    price: 2.3,
    unit: 'pro 200 g',
    stockLabel: 'Frisch geschnitten',
    stockLevel: 'fresh',
    image: '/images/products/spinat.jpg',
    description: 'Vitaminreicher Spinat aus den vertikalen A-Frames in Etage 3 & 4 — deckt einen wesentlichen Teil des Vitaminbedarfs für 1.000 Personen.',
    origin: 'Gemüseturm · Ebene 3 & 4',
    row: 'C7',
    badge: 'Vitaminreich',
    tags: ['blaues LED', 'nährstoffreich', 'frisch'],
  },
  {
    id: 'rucola',
    name: 'Rucola',
    category: 'Blattgemüse',
    price: 2.1,
    unit: 'pro 100 g',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/rucola.jpg',
    description: 'Würziger Rucola aus den mehrlagigen Regalsystemen — dank blauem LED-Spektrum intensives Blattaroma und schnelles Nachwachsen.',
    origin: 'Gemüseturm · Ebene 3 & 4',
    row: 'D2',
    badge: 'Schnellwüchsig',
    tags: ['A-Frame', 'würzig', 'erntefrisch'],
  },
  {
    id: 'pak-choi',
    name: 'Pak Choi',
    category: 'Blattgemüse',
    price: 2.7,
    unit: 'pro Kopf',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/pak-choi.jpg',
    description: 'Zartes Pak Choi aus Etage 3 & 4 — ideal für Asia-Gerichte, Woks und kurze Garzeiten. Optimal angebaut im blauen LED-Spektrum.',
    origin: 'Gemüseturm · Ebene 3 & 4',
    row: 'D5',
    badge: 'Asia-Küche',
    tags: ['blaues LED', 'zart', 'lokal'],
  },
  {
    id: 'gruenkohl',
    name: 'Grünkohl',
    category: 'Blattgemüse',
    price: 3.0,
    unit: 'pro 300 g',
    stockLabel: 'Kleine Ernte',
    stockLevel: 'limited',
    image: '/images/products/mangold.jpg',
    description: 'Nährstoffdichter Grünkohl aus den vertikalen Regalen in Etage 3 & 4 — angebaut unter blauem LED-Spektrum für maximales Blattwachstum.',
    origin: 'Gemüseturm · Ebene 3 & 4',
    row: 'D8',
    badge: 'Superfood',
    tags: ['blaues LED', 'nährstoffreich', 'saisonal'],
  },

  // ── Ebene 5 & 6: Fruchtgemüse (Hochrankensysteme, Hummelvölker, rotes LED) ──
  {
    id: 'tomaten',
    name: 'Tomaten',
    category: 'Fruchtgemüse',
    price: 3.8,
    unit: 'pro 500 g',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/kirschtomaten.jpg',
    description: 'Saftige Tomaten aus den 4,50 m Hochrankensystemen in Etage 5 & 6 — natürlich bestäubt durch Hummelvölker, gereift unter rotem LED-Spektrum.',
    origin: 'Gemüseturm · Ebene 5 & 6',
    row: 'E4',
    badge: 'Hummelbestäubt',
    tags: ['Hochranksystem', 'rotes LED', 'natürlich bestäubt'],
  },
  {
    id: 'gurken',
    name: 'Gurken',
    category: 'Fruchtgemüse',
    price: 2.6,
    unit: 'pro Stück',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/gurke.jpg',
    description: 'Frische Gurken von den 4,50 m Drahtranksystemen in Etage 5 & 6 — hohe Luftfeuchtigkeit und rotes LED-Spektrum fördern die Fruchtbildung.',
    origin: 'Gemüseturm · Ebene 5 & 6',
    row: 'E8',
    badge: 'Knackfrisch',
    tags: ['Hochranksystem', 'Hummelvölker', 'frisch'],
  },
  {
    id: 'paprika',
    name: 'Paprika',
    category: 'Fruchtgemüse',
    price: 3.4,
    unit: 'pro 3 Stück',
    stockLabel: 'Erntebereit',
    stockLevel: 'fresh',
    image: '/images/products/paprika.jpg',
    description: 'Bunte Paprika aus den Hochrankesystemen in Etage 5 & 6 — Hummelvölker sorgen für natürliche Bestäubung, rotes LED für optimale Fruchtreife.',
    origin: 'Gemüseturm · Ebene 5 & 6',
    row: 'F2',
    badge: 'Farbenpracht',
    tags: ['rotes LED', 'natürlich bestäubt', 'lokal'],
  },
  {
    id: 'auberginen',
    name: 'Auberginen',
    category: 'Fruchtgemüse',
    price: 3.2,
    unit: 'pro Stück',
    stockLabel: 'Kleine Ernte',
    stockLevel: 'limited',
    image: '/images/products/auberginen.jpg',
    description: 'Zarte Auberginen aus den hohen Rankzonen in Etage 5 & 6 — angebaut unter hoher Luftfeuchtigkeit und rotem LED-Spektrum für volle Fruchtbildung.',
    origin: 'Gemüseturm · Ebene 5 & 6',
    row: 'F6',
    badge: 'Besondere Ernte',
    tags: ['Hochranksystem', 'rotes LED', 'besonders'],
  },

  // ── Ebene 7 & 8: Kräuter, Arzneipflanzen & Früchte (Glasdach, viel Licht) ──
  {
    id: 'basilikum',
    name: 'Basilikum',
    category: 'Kräuter & Früchte',
    price: 1.8,
    unit: 'pro Bund',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/basilikum.jpg',
    description: 'Aromatisches Basilikum aus der Kräuterküche in Etage 7 & 8 — natürliches Tageslicht durch das Glasdach und optimale Luftfeuchtigkeit für intensiven Geschmack.',
    origin: 'Gemüseturm · Ebene 7 & 8',
    row: 'G1',
    badge: 'Küchenklassiker',
    tags: ['Glasdach', 'Kräuterküche', 'aromatisch'],
  },
  {
    id: 'petersilie',
    name: 'Petersilie',
    category: 'Kräuter & Früchte',
    price: 1.5,
    unit: 'pro Bund',
    stockLabel: 'Auf Lager',
    stockLevel: 'ready',
    image: '/images/products/petersilie.jpg',
    description: 'Frische Petersilie aus der Kräuterzone in Etage 7 & 8 — unter dem Glasdach mit natürlichem Lichteinfall angebaut.',
    origin: 'Gemüseturm · Ebene 7 & 8',
    row: 'G4',
    badge: 'Preiswert',
    tags: ['Glasdach', 'würzig', 'erntefrisch'],
  },
  {
    id: 'erdbeeren',
    name: 'Erdbeeren',
    category: 'Kräuter & Früchte',
    price: 4.2,
    unit: 'pro 250 g',
    stockLabel: 'Kleine Ernte',
    stockLevel: 'limited',
    image: '/images/products/erdbeeren.jpg',
    description: 'Aromatische Erdbeeren aus der lichtdurchfluteten Dachetage 8 — das Glasdach liefert maximales natürliches Licht für intensiv süße Früchte.',
    origin: 'Gemüseturm · Ebene 8 · Glasdach',
    row: 'H2',
    badge: 'Nur kleine Menge',
    tags: ['Glasdach', 'natürliches Licht', 'besonders'],
  },
  {
    id: 'himbeeren',
    name: 'Himbeeren',
    category: 'Kräuter & Früchte',
    price: 4.8,
    unit: 'pro 150 g',
    stockLabel: 'Kleine Ernte',
    stockLevel: 'limited',
    image: '/images/products/himbeeren.jpg',
    description: 'Saftige Himbeeren aus der obersten Dachetage — unter dem Glasdach mit natürlichem Licht und hoher Luftfeuchtigkeit kultiviert.',
    origin: 'Gemüseturm · Ebene 8 · Glasdach',
    row: 'H6',
    badge: 'Premium',
    tags: ['Glasdach', 'natürliches Licht', 'selten'],
  },
]
